table Parameter
	lineageTag: cf3c1e38-cd50-45a2-bc0c-ef1dbbe5d09a

	measure 'Parameter Value' = SELECTEDVALUE('Parameter'[Parameter])
		formatString: 0
		lineageTag: f251d1df-d6a7-4314-ae0b-f245b440d10a

	column Parameter
		formatString: 0
		lineageTag: f3104da3-fbc8-4824-af9d-520662cf12fa
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Parameter = calculated
		mode: import
		source = GENERATESERIES(1, max(FACT_TurnaroundTime[TurnaroundTime]), 1)

	annotation PBI_Id = 048c2d33d6f44077b22aa371594108ef

