DEFINE
    MEASURE 'FACT_TaskQuote'[Count of Converted] = 
        CALCULATE(
            DISTINCTCOUNT('FACT_TaskQuote'[QuoteNumLine]),
            'FACT_TaskQuote'[ReasonType] = "W"
        )

    MEASURE 'FACT_TaskQuote'[MinCreateDate] = 
        CALCULATE(
            MIN('FACT_TaskQuote'[CreateDate]),
            ALLEXCEPT('FACT_TaskQuote', 'FACT_TaskQuote'[QuoteNum], 'FACT_TaskQuote'[CreateDate])
        )

    MEASURE 'FACT_TaskQuote'[MaxCompleteDate] = 
        CALCULATE(
            MAX('FACT_TaskQuote'[CompleteDate]),
            ALLEXCEPT('FACT_TaskQuote', 'FACT_TaskQuote'[QuoteNum], 'FACT_TaskQuote'[CreateDate])
        )

    MEASURE 'FACT_TaskQuote'[RFQ Lead Time] = 
        DATEDIFF([MinCreateDate], [MaxCompleteDate], DAY)

    MEASURE 'FACT_TaskQuote'[Avg RFQ Lead Time] = 
        CALCULATE(
            AVERAGEX('FACT_TaskQuote', [RFQ Lead Time]),
            FILTER('FACT_TaskQuote', 'FACT_TaskQuote'[ReasonType] <> "")
        )

    MEASURE 'FACT_TaskQuote'[Avg Response Time] = 
        AVERAGEX('FACT_TaskQuote', [Response Time])

    MEASURE 'FACT_TaskQuote'[Response Time] = 
        ABS(DATEDIFF(MAX('FACT_TaskQuote'[CompleteDate]), MIN('FACT_TaskQuote'[CreateDate]), DAY)) - 
        ABS(DATEDIFF(MAX('FACT_TaskQuote'[CompleteDate]), MIN('FACT_TaskQuote'[CreateDate]), WEEK)) * 2