table DIM_Industry
	lineageTag: b31cb453-7121-4ba1-8d9e-c38ae3528918

	column IndustryKey
		dataType: string
		lineageTag: 081723c0-8bf7-432c-81ce-4fcec6c8ed36
		summarizeBy: none
		sourceColumn: IndustryKey

		annotation SummarizationSetBy = Automatic

	column Industry
		dataType: string
		lineageTag: 60152106-b771-4586-b3b8-caf08af69f6c
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

	column 'Major Industry'
		dataType: string
		lineageTag: 69200a96-753c-4595-938b-3f8a161fe401
		summarizeBy: none
		sourceColumn: Major Industry

		annotation SummarizationSetBy = Automatic

	column 'Minor Industry'
		dataType: string
		lineageTag: 5b5a6f12-7d9f-47f0-9e0e-6a4f93b961de
		summarizeBy: none
		sourceColumn: Minor Industry

		annotation SummarizationSetBy = Automatic

	column SupportingDefinition
		dataType: string
		lineageTag: 175d928c-17df-40f4-a26d-5c2bb1a39c0a
		summarizeBy: none
		sourceColumn: SupportingDefinition

		annotation SummarizationSetBy = Automatic

	column MajorMMS
		dataType: string
		lineageTag: 2f512dcf-f823-4953-ba20-8db668fb4268
		summarizeBy: none
		sourceColumn: MajorMMS

		annotation SummarizationSetBy = Automatic

	column MinorMMS
		dataType: string
		lineageTag: 8aea0504-9e3f-4faf-99ff-5c85d9086e3a
		summarizeBy: none
		sourceColumn: MinorMMS

		annotation SummarizationSetBy = Automatic

	column DSDTMarket
		dataType: string
		lineageTag: d5a100f7-2307-44cb-a339-fd6337bc26f4
		summarizeBy: none
		sourceColumn: DSDTMarket

		annotation SummarizationSetBy = Automatic

	column DSDTSubMarketCode
		dataType: string
		lineageTag: 42c84d99-3e14-4d92-b3e4-87440ddbfc87
		summarizeBy: none
		sourceColumn: DSDTSubMarketCode

		annotation SummarizationSetBy = Automatic

	column DSDTSubMarket
		dataType: string
		lineageTag: f3b50fbb-39a8-452a-960d-705dac403f2e
		summarizeBy: none
		sourceColumn: DSDTSubMarket

		annotation SummarizationSetBy = Automatic

	partition DIM_Industry = m
		mode: import
		source =
				let
				    Source = Sql.Database("atpc-dwh-db1.tpcwire.com", "ODIN-Production"),
				    MIMIR_DIM_Territory = Source{[Schema="MIMIR",Item="DIM_Industry"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(MIMIR_DIM_Territory,{{"MajorIndustry", "Major Industry"}, {"MinorIndustry", "Minor Industry"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

