table FACT_TaskQuote
	lineageTag: 1e26d9fc-81d8-439b-b86a-6f697fb7b37b

	measure 'Count of Converted' = ```
			
			        CALCULATE(
			            DISTINCTCOUNT('FACT_TaskQuote'[QuoteNumLine]),
			            'FACT_TaskQuote'[ReasonType] = "W"
			        )
			
			    
			```
		formatString: 0
		lineageTag: 6b658f4f-b972-47cc-a838-bf391cbf4b89

	measure MinCreateDate = ```
			
			        CALCULATE(
			            MIN('FACT_TaskQuote'[CreateDate]),
			            ALLEXCEPT('FACT_TaskQuote', 'FACT_TaskQuote'[QuoteNum], 'FACT_TaskQuote'[CreateDate])
			        )
			
			    
			```
		formatString: m/d/yyyy
		lineageTag: ad6fa538-e0b2-4cae-87f8-5c87e5b0d0a9

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure MaxCompleteDate = ```
			
			        CALCULATE(
			            MAX('FACT_TaskQuote'[CompleteDate]),
			            ALLEXCEPT('FACT_TaskQuote', 'FACT_TaskQuote'[QuoteNum], 'FACT_TaskQuote'[CreateDate])
			        )
			
			    
			```
		formatString: m/d/yyyy
		lineageTag: 92c0089f-2eed-4e25-a93d-028eb93c0f03

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	measure 'RFQ Lead Time' = ```
			
			        DATEDIFF([MinCreateDate], [MaxCompleteDate], DAY)
			
			    
			```
		formatString: 0
		lineageTag: 72f8feca-ed85-4548-a20c-47f03d9fb3a6

	measure 'Avg RFQ Lead Time' = ```
			
			        CALCULATE(
			            AVERAGEX('FACT_TaskQuote', [RFQ Lead Time]),
			            FILTER('FACT_TaskQuote', 'FACT_TaskQuote'[ReasonType] <> "")
			        )
			
			    
			```
		lineageTag: ce59faf0-6c4f-4b8d-8359-cdfd6822e6a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Response Time' = ```
			
			        AVERAGEX('FACT_TaskQuote', [Response Time])
			
			    
			```
		formatString: 0.00
		lineageTag: 40722dd1-9a28-4e92-a807-98a30a94b481

	measure 'Response Time' = ```
			
			        ABS(DATEDIFF(MAX('FACT_TaskQuote'[CompleteDate]), MIN('FACT_TaskQuote'[CreateDate]), DAY)) - 
			        ABS(DATEDIFF(MAX('FACT_TaskQuote'[CompleteDate]), MIN('FACT_TaskQuote'[CreateDate]), WEEK)) * 2
			```
		formatString: 0
		lineageTag: 7e91b542-c516-4b59-878b-31b075c46f24

		annotation PBI_FormatHint = {"isDecimal":true}

	column Company
		dataType: string
		lineageTag: b192857a-d704-4877-8a1a-e8546873b5bf
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column TaskCustNum
		dataType: string
		lineageTag: 66810d86-22a4-4362-96cf-cfea0f424942
		summarizeBy: none
		sourceColumn: TaskCustNum

		annotation SummarizationSetBy = Automatic

	column TaskSetDescription
		dataType: string
		lineageTag: 06f69e2d-2266-45f9-993a-520fa266096b
		summarizeBy: none
		sourceColumn: TaskSetDescription

		annotation SummarizationSetBy = Automatic

	column CreateDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: bac303b4-4e00-4a7b-b16d-e5de365d4153
		summarizeBy: none
		sourceColumn: CreateDate

		variation Variation
			isDefault
			relationship: a48f02ff-470f-4fdd-aa06-12abd72a4598
			defaultHierarchy: LocalDateTable_b9013ccf-0978-4371-b0bc-bdf5830ce28a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column RFQType
		dataType: string
		lineageTag: 9d09fc75-5b68-4500-83d5-3c15c2f43353
		summarizeBy: none
		sourceColumn: RFQType

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 0ce0b351-1203-4f3d-955a-019861ec921b
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: 273f2ee7-cfed-4e6d-8d6c-eb50e0108b5a
			defaultHierarchy: LocalDateTable_28cfdf9d-3c1c-492d-be7d-6597675c533b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DueDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c0f63896-b05c-4c75-b4dc-af323ae7163b
		summarizeBy: none
		sourceColumn: DueDate

		variation Variation
			isDefault
			relationship: 2ba1df88-5dfc-4159-a613-b96927986a57
			defaultHierarchy: LocalDateTable_288c6134-3dc4-4e8f-9e98-da459c4415b9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CompleteDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: c342a102-3d7c-441d-b00c-8f5d9b0bbac0
		summarizeBy: none
		sourceColumn: CompleteDate

		variation Variation
			isDefault
			relationship: 3b25e0bb-2820-47fb-99ba-5a01960bebe0
			defaultHierarchy: LocalDateTable_000d719a-7689-4ecf-afb0-8991ce0ed1c2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column BTName
		dataType: string
		lineageTag: 0f05616f-37b9-4f76-9dc6-35c67dec2611
		summarizeBy: none
		sourceColumn: BTName

		annotation SummarizationSetBy = Automatic

	column QuoteNum
		dataType: string
		lineageTag: 136789a8-8775-4771-9b30-c8634401056d
		summarizeBy: none
		sourceColumn: QuoteNum

		annotation SummarizationSetBy = Automatic

	column RevisionNum
		dataType: string
		lineageTag: 7be7b421-8ede-4f5a-9503-65052e261bf7
		summarizeBy: none
		sourceColumn: RevisionNum

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 77053119-7dca-4be5-9cf6-dfa5153bcbda
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column TerritoryID
		dataType: string
		lineageTag: 6bc2a327-5638-4d65-a6dd-1f2af98ec702
		summarizeBy: none
		sourceColumn: TerritoryID

		annotation SummarizationSetBy = Automatic

	column TerritoryDesc
		dataType: string
		lineageTag: ab7baa27-1df1-42bc-8cd7-82955f632b6f
		summarizeBy: none
		sourceColumn: TerritoryDesc

		annotation SummarizationSetBy = Automatic

	column Conclusion
		dataType: string
		lineageTag: 6c5beef1-b1a8-4780-a5ae-cf971d71613d
		summarizeBy: none
		sourceColumn: Conclusion

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 17dbacfe-470b-4600-9c55-57f0d8dccc55
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column ReasonType
		dataType: string
		lineageTag: c6d1dd83-cd73-446d-9694-5e6d1410ba23
		summarizeBy: none
		sourceColumn: ReasonType

		annotation SummarizationSetBy = Automatic

	column CustID
		dataType: string
		lineageTag: c8bdecc3-ffa6-4499-9c25-1189cbd4d424
		summarizeBy: none
		sourceColumn: CustID

		annotation SummarizationSetBy = Automatic

	column TaskDescription
		dataType: string
		lineageTag: 992ad570-d9ad-4513-9b79-f6a75e149bee
		summarizeBy: none
		sourceColumn: TaskDescription

		annotation SummarizationSetBy = Automatic

	column SalesRepName
		dataType: string
		lineageTag: d8f6b388-7995-4ab0-aa40-ab66f866a49d
		summarizeBy: none
		sourceColumn: SalesRepName

		annotation SummarizationSetBy = Automatic

	column PartNum
		dataType: string
		lineageTag: 94de0536-e5d1-413a-805d-eb03ab70543d
		summarizeBy: none
		sourceColumn: PartNum

		annotation SummarizationSetBy = Automatic

	column ECOTask
		dataType: string
		lineageTag: 8a0acf08-4693-412d-9d0a-ad7a854d2ce3
		summarizeBy: none
		sourceColumn: ECOTask

		annotation SummarizationSetBy = Automatic

	column ProdGroupDescription
		dataType: string
		lineageTag: 3c08de8b-9870-4225-b56d-87ee79fa9f0c
		summarizeBy: none
		sourceColumn: ProdGroupDescription

		annotation SummarizationSetBy = Automatic

	column QuoteLine
		dataType: int64
		formatString: 0
		lineageTag: 21c136d0-bb36-482a-b901-63950325ed0a
		summarizeBy: sum
		sourceColumn: QuoteLine

		annotation SummarizationSetBy = Automatic

	column QuoteNumLine
		dataType: string
		lineageTag: 4d02d166-2fc0-448d-b7cd-49670ed24527
		summarizeBy: none
		sourceColumn: QuoteNumLine

		annotation SummarizationSetBy = Automatic

	column StartDateKey = FORMAT(FACT_TaskQuote[StartDate], "yyyymmdd")
		lineageTag: 39e00a3b-2bc4-4bc0-8291-6669a252a2d3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CompleteDateKey = FORMAT(FACT_TaskQuote[CompleteDate], "yyyymmdd")
		lineageTag: 6a694f76-0003-41d6-90f3-b61d3a077656
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition FACT_TaskQuote = m
		mode: import
		source =
				let
				    Source = Sql.Database("atpc-dwh-db1.tpcwire.com", "ODIN-Production"),
				    MIMIR_Fact_TaskQuote = Source{[Schema="MIMIR",Item="FACT_TaskQuote"]}[Data]
				in
				    MIMIR_Fact_TaskQuote

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

